ak/tk12.1-12.3
sai0nara/Simple_BDD_Framework pull request #61
Opened 2021-12-23 07:10 UTC by AlekseyKoks-in

Добавлены ТК 12.1-12.3

2021-12-29 06:04 UTC, TGolovanova requested changes

2021-12-29 06:04 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoAddAccountAdministrators.java
> +    private SelenideElement title = $x("//div[@id = 'content']/h1");
по-моему, так точнее будет: //a[@href = '/admin/core/accountadmin/add/']

2021-12-29 06:04 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement infoblock = $("#employee_form > p");
тут кажется чего-то не хватает, как минимум странный поиск элемента

2021-12-29 06:04 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement surname = $x("//input[@name='surname']");
Если это страница восстановления удаленного сотрудника, то //select[@name='employee']

2021-12-29 06:04 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoRestoreAccountAdministrators.java
> +    private ElementsCollection employee = $$("//select[@name = 'employee']");
неверный Xpath, вот так будет: //table[@id="change-history"]/tbody/tr/td

2021-12-29 07:38 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoAddAccountAdministrators.java
> +    private SelenideElement title = $x("//div[@id = 'content']/h1");
Этот xpath в единственном экземпляре, к тому же твой xpath здесь не работает.

2021-12-29 07:41 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement infoblock = $("#employee_form > p");
Исправил, т.к. данный элемент не нужен в тестах 12.1-12.3 удалил его

2021-12-29 07:42 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement surname = $x("//input[@name='surname']");
Исправил

2021-12-29 07:42 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoRestoreAccountAdministrators.java
> +    private ElementsCollection employee = $$("//select[@name = 'employee']");
Исправил

2021-12-29 08:00 UTC, TGolovanova approved these changes

2021-12-30 11:39 UTC, Archibald5 approved these changes

2021-12-30 14:25 UTC, AbdullaevTeymur approved these changes

2022-01-10 07:26 UTC, merged