Добавлены TK 14.1-14.3
sai0nara/Simple_BDD_Framework pull request #66
Opened 2021-12-28 09:54 UTC by AlekseyKoks-in

2021-12-28 18:01 UTC, valeriandr411 approved these changes

2021-12-29 06:28 UTC, TGolovanova requested changes

2021-12-29 06:28 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement infoblock = $("#employee_form > p");
тот же вопрос

2021-12-29 06:28 UTC, TGolovanova commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement surname = $x("//input[@name='surname']");
тот же вопрос

2021-12-29 08:55 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement infoblock = $("#employee_form > p");
Исправил

2021-12-29 08:55 UTC, AlekseyKoks-in commented on autotest-web/src/main/java/pages/account_administrators/DjangoReturnAccountAdministrators.java
> +    private SelenideElement surname = $x("//input[@name='surname']");
Исправил

2021-12-30 09:45 UTC, TGolovanova approved these changes

2021-12-30 12:30 UTC, AbdullaevTeymur commented
Подтяни изменения, DjangoAdministrationPage отличается от той, что в мастере

2022-01-11 07:54 UTC, AbdullaevTeymur approved these changes

2022-01-12 07:45 UTC, Archibald5 approved these changes

2022-01-18 12:31 UTC, merged